import { PrismaClient } from "@prisma/client";
import { writeFileSync } from "node:fs";

/**
 * Exports CMS pages and navigation from the database into seed data.
 *
 * Run after changing content that should ship with a fresh install; the output
 * is what `prisma/seed.ts` replays, so `db:reset && db:seed` reproduces the
 * site exactly rather than leaving a new environment with an empty CMS.
 *
 *     npx tsx scripts/export-content-seed.ts
 */
async function main() {
  const prisma = new PrismaClient();

  const pages = await prisma.page.findMany({
    where: { deletedAt: null },
    orderBy: { slug: "asc" },
    select: {
      slug: true,
      title: true,
      description: true,
      keywords: true,
      status: true,
      breadcrumb: true,
      faqTopic: true,
      brand: { select: { slug: true } },
      sections: {
        orderBy: { displayOrder: "asc" },
        select: { type: true, displayOrder: true, visible: true, data: true },
      },
    },
  });

  const nav = await prisma.navigationItem.findMany({
    orderBy: [{ menu: "asc" }, { displayOrder: "asc" }],
    select: { id: true, menu: true, label: true, href: true, description: true, parentId: true, displayOrder: true },
  });

  // Rewrite cuids as stable, readable keys so the seed file does not churn on
  // every export and a reviewer can follow the tree.
  const keyById = new Map<string, string>();
  const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  for (const item of nav) {
    const parentKey = item.parentId ? keyById.get(item.parentId) : undefined;
    keyById.set(item.id, `${parentKey ? `${parentKey}.` : ""}${slug(item.label)}`);
  }

  const navSeed = nav.map((item) => ({
    key: keyById.get(item.id)!,
    parentKey: item.parentId ? keyById.get(item.parentId)! : null,
    menu: item.menu,
    label: item.label,
    href: item.href,
    description: item.description,
    displayOrder: item.displayOrder,
  }));

  const pageSeed = pages.map((page) => ({
    slug: page.slug,
    title: page.title,
    description: page.description,
    keywords: page.keywords,
    status: page.status,
    breadcrumb: page.breadcrumb,
    brandSlug: page.brand?.slug ?? null,
    faqTopic: page.faqTopic,
    sections: page.sections,
  }));

  const header = `/**
 * CMS pages and navigation shipped with a fresh install.
 *
 * Generated by scripts/export-content-seed.ts — edit content in the admin panel
 * and re-export rather than editing this file by hand.
 */
import type { NavigationMenu, PageSectionType, PageStatus } from "@prisma/client";

export type PageSeed = {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  status: PageStatus;
  breadcrumb: unknown;
  brandSlug: string | null;
  faqTopic: string | null;
  sections: Array<{
    type: PageSectionType;
    displayOrder: number;
    visible: boolean;
    data: unknown;
  }>;
};

export type NavigationSeed = {
  key: string;
  parentKey: string | null;
  menu: NavigationMenu;
  label: string;
  href: string | null;
  description: string | null;
  displayOrder: number;
};

`;

  writeFileSync(
    "prisma/seed-data/pages.ts",
    `${header}export const pageSeeds: PageSeed[] = ${JSON.stringify(pageSeed, null, 2)};\n\nexport const navigationSeeds: NavigationSeed[] = ${JSON.stringify(navSeed, null, 2)};\n`,
  );

  console.log(`  exported ${pageSeed.length} pages, ${navSeed.length} navigation items`);
  await prisma.$disconnect();
}

void main();
