import { PrismaClient } from "@prisma/client";
import { writeFileSync } from "node:fs";

/**
 * Exports CMS pages and navigation from the database into seed data.
 *
 * Run after changing content that should ship with a fresh install; the output
 * is what `prisma/seed.ts` replays, so `db:reset && db:seed` reproduces the
 * site exactly rather than leaving a new environment with an empty CMS.
 *
 *     npx tsx scripts/export-content-seed.ts
 */
async function main() {
  const prisma = new PrismaClient();

  const pages = await prisma.page.findMany({
    where: { deletedAt: null },
    orderBy: { slug: "asc" },
    select: {
      slug: true,
      title: true,
      description: true,
      keywords: true,
      status: true,
      breadcrumb: true,
      faqTopic: true,
      brand: { select: { slug: true } },
      sections: {
        // `type` breaks a tie so two blocks sharing a displayOrder do not swap
        // places between exports and make the seed file churn.
        orderBy: [{ displayOrder: "asc" }, { type: "asc" }],
        select: { type: true, displayOrder: true, visible: true, data: true },
      },
    },
  });

  const nav = await prisma.navigationItem.findMany({
    // Siblings routinely share a displayOrder, so `label` breaks the tie. Left
    // ambiguous, the row order came out of the heap and changed between
    // exports, which made the seed file churn on every run for no reason.
    orderBy: [{ menu: "asc" }, { displayOrder: "asc" }, { label: "asc" }],
    select: { id: true, menu: true, label: true, href: true, description: true, parentId: true, displayOrder: true },
  });

  /**
   * Rewrites cuids as stable, readable keys, so the seed file does not carry
   * ids that change on every fresh install and a reviewer can follow the tree.
   *
   * Walked parents-first rather than in row order. Reading the list in order
   * and looking each parent up as it went silently produced `parentKey: null`
   * whenever a child happened to sort ahead of its parent — the export
   * succeeded and a fresh install got a flat menu.
   */
  const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const childrenOf = new Map<string | null, typeof nav>();
  for (const item of nav) {
    const list = childrenOf.get(item.parentId) ?? [];
    list.push(item);
    childrenOf.set(item.parentId, list);
  }

  const keyById = new Map<string, string>();
  const ordered: typeof nav = [];
  const walk = (parentId: string | null, prefix: string) => {
    for (const item of childrenOf.get(parentId) ?? []) {
      // Scoped by menu at the root. Without it a header "Services" and a
      // footer "Services" both keyed as `services`, the seeder's key -> id map
      // kept whichever it wrote last, and every child naming that parent
      // attached to it — a fresh install put the header's submenu under the
      // footer heading.
      const key = `${prefix || `${item.menu.toLowerCase()}:`}${slug(item.label)}`;
      keyById.set(item.id, key);
      ordered.push(item);
      walk(item.id, `${key}.`);
    }
  };
  walk(null, "");

  const seen = new Set<string>();
  for (const key of keyById.values()) {
    if (seen.has(key)) throw new Error(`navigation key is not unique: ${key}`);
    seen.add(key);
  }

  if (ordered.length !== nav.length) {
    // Only reachable if a row's parent was filtered out or the tree contains a
    // cycle. Either way the export would be silently incomplete.
    throw new Error(`navigation tree is not fully connected: ${ordered.length} of ${nav.length} reachable`);
  }

  const navSeed = ordered.map((item) => ({
    key: keyById.get(item.id)!,
    parentKey: item.parentId ? keyById.get(item.parentId)! : null,
    menu: item.menu,
    label: item.label,
    href: item.href,
    description: item.description,
    displayOrder: item.displayOrder,
  }));

  const pageSeed = pages.map((page) => ({
    slug: page.slug,
    title: page.title,
    description: page.description,
    keywords: page.keywords,
    status: page.status,
    breadcrumb: page.breadcrumb,
    brandSlug: page.brand?.slug ?? null,
    faqTopic: page.faqTopic,
    sections: page.sections,
  }));

  const header = `/**
 * CMS pages and navigation shipped with a fresh install.
 *
 * Generated by scripts/export-content-seed.ts — edit content in the admin panel
 * and re-export rather than editing this file by hand.
 */
import type { NavigationMenu, PageSectionType, PageStatus } from "@prisma/client";

export type PageSeed = {
  slug: string;
  title: string;
  description: string;
  keywords: string[];
  status: PageStatus;
  breadcrumb: unknown;
  brandSlug: string | null;
  faqTopic: string | null;
  sections: Array<{
    type: PageSectionType;
    displayOrder: number;
    visible: boolean;
    data: unknown;
  }>;
};

export type NavigationSeed = {
  key: string;
  parentKey: string | null;
  menu: NavigationMenu;
  label: string;
  href: string | null;
  description: string | null;
  displayOrder: number;
};

`;

  writeFileSync(
    "prisma/seed-data/pages.ts",
    `${header}export const pageSeeds: PageSeed[] = ${JSON.stringify(pageSeed, null, 2)};\n\nexport const navigationSeeds: NavigationSeed[] = ${JSON.stringify(navSeed, null, 2)};\n`,
  );

  console.log(`  exported ${pageSeed.length} pages, ${navSeed.length} navigation items`);
  await prisma.$disconnect();
}

void main();
