import { readFileSync, writeFileSync } from "node:fs";
import { readImage } from "@/lib/pdf/image";

const mark = (file: string) => readImage(readFileSync(`public/certifications/${file}`));
import { renderQuotationPdf } from "@/lib/pdf/quotation";

const party = {
  name: "MIT ADT University",
  addressLines: ["Loni Kalbhor, Solapur Highway", "Pune, Maharashtra 412201", "India"],
  gstin: "27AAAJM2218H1ZC",
  pan: null,
  contactName: "Dr. Suresh Rao",
  phone: "+91 70888 28088",
  email: "itpurchase@example.edu.in",
  state: "Maharashtra",
};

const bytes = renderQuotationPdf({
  reference: "QTE-2026-4F7K2P",
  documentNo: "TZ/QT/2026-27/0042",
  referenceNo: "ENQ-2026-9XM4TQ",
  version: 2,
  currency: "INR",
  subtotalMinor: 112317100,
  discountMinor: 4064000,
  taxMinor: 20217078,
  totalMinor: 132534178,
  validUntil: new Date("2026-09-16"),
  issuedAt: new Date("2026-08-17"),
  notes:
    "Thank you for your enquiry. We are pleased to submit our best offer for the Microsoft licensing and endpoint security requirement discussed. All pricing below is inclusive of deployment support.",
  status: "SENT",
  paymentTerms: "50% advance, balance on delivery",
  salesExecutive: "Abhinav Jain",
  quotedTo: party,
  billing: party,
  shipping: {
    ...party,
    addressLines: ["Rajbaug Campus, Gate No. 2", "Loni Kalbhor, Maharashtra 412201", "India"],
  },
  lines: [
    {
      productName: "Microsoft 365 Business Standard",
      description: "Annual subscription - includes Office apps, Exchange, Teams, SharePoint",
      brandName: "Microsoft",
      sku: "CFQ7TTC0LH18",
      hsnCode: "997331",
      quantity: 60,
      unitLabel: "Users",
      unitPriceMinor: 560000,
      discountMinor: 1680000,
      gstRatePercent: 18,
      lineTotalMinor: 31920000,
    },
    {
      productName: "Microsoft 365 Business Premium",
      description: "Annual subscription - advanced security, Intune device management",
      brandName: "Microsoft",
      sku: "CFQ7TTC0LCHC",
      hsnCode: "997331",
      quantity: 15,
      unitLabel: "Users",
      unitPriceMinor: 890000,
      discountMinor: 667500,
      gstRatePercent: 18,
      lineTotalMinor: 12682500,
    },
    {
      productName: "Windows 11 Pro",
      description: "OEM licence, per device",
      brandName: "Microsoft",
      sku: "FQC-10529",
      hsnCode: "997331",
      quantity: 25,
      unitLabel: "Nos",
      unitPriceMinor: 1150000,
      discountMinor: 0,
      gstRatePercent: 18,
      lineTotalMinor: 28750000,
    },
    {
      productName: "Kaspersky Endpoint Security for Business",
      description: "Advanced tier, 1-year licence",
      brandName: "Kaspersky",
      sku: "KL4867XAKFS",
      hsnCode: "997331",
      quantity: 100,
      unitLabel: "Nodes",
      unitPriceMinor: 145000,
      discountMinor: 1160000,
      gstRatePercent: 18,
      lineTotalMinor: 13340000,
    },
    {
      productName: "Implementation and Migration Support",
      description: "Tenant setup, mailbox migration, on-site handover and admin training",
      brandName: null,
      sku: "SVC-IMPL-01",
      hsnCode: "998313",
      quantity: 1,
      unitLabel: "Project",
      unitPriceMinor: 8500000,
      discountMinor: 0,
      gstRatePercent: 18,
      lineTotalMinor: 8500000,
    },
    {
      productName: "HP ProBook 450 G10 Notebook",
      description: "Core i5-1335U, 16 GB, 512 GB SSD, Windows 11 Pro",
      brandName: "HP",
      sku: "9X4M2PA",
      hsnCode: "847130",
      quantity: 12,
      unitLabel: "Nos",
      unitPriceMinor: 6800000,
      discountMinor: 556600,
      gstRatePercent: 18,
      lineTotalMinor: 17124600,
    },
  ],
  config: {
    tradingName: "TechZoid",
    legalName: "TechZoid Technologies Private Limited",
    entityName: "TechZoid Technologies Private Limited",
    tagline: "One procurement partner. Multiple technology brands.",
    url: "https://www.techzoidtechnologies.com",
    email: { sales: "sales@techzoidtechnologies.com", support: null, enterprise: null },
    phone: { sales: "+91 98765 43210", support: null },
    grievance: { name: null, email: null, phone: null },
    address: {
      line1: "407, 4th Floor, Pearl Business Park",
      line2: "Netaji Subhash Place, Pitampura",
      city: "New Delhi",
      state: "Delhi",
      postcode: "110034",
      country: "India",
    },
    hasAddress: true,
    formattedAddress: null,
    gstin: "07AAICT5606J1Z4",
    cin: "U72900DL2021PTC380025",
    supportHours: null,
    quoteTerms:
      "Prices are exclusive of any charges not stated above.\nDelivery within 5 to 7 working days of a confirmed purchase order, subject to publisher availability.\nLicence keys are issued to the registered administrator email address on record.\nThis quotation is an offer to supply and does not reserve stock or pricing beyond the validity date.\nAny statutory levy introduced after the date of this quotation will apply at actuals.",
    rates: { USD: null, AED: null },
    secondaryEntity: {
      name: "TechZoid Technologies \u2014 UAE office",
      address: "Office C1-1F-SF2571, Ajman Free Zone C1 Building, Ajman Free Zone, Dubai",
      phone: "+971 58 939 7239",
    },
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as any,
  certifications: [
    { standard: "ISO 9001:2015", title: "Quality Management System", reference: "QMS-0001", image: mark("ISO-9001-2015.png") },
    { standard: "ISO 27001:2022", title: "Information Security Management System", reference: "ISMS-0001", image: mark("ISO-27001-2022.png") },
    { standard: "ISO/IEC 20000-1:2018", title: "IT Service Management System", reference: "ITSM-0001", image: mark("ISO-IEC-20000-1-2018.png") },
  ],
  accreditations: [],
  logo: null,
  banking: {
    bankName: "Sample Bank",
    accountName: "TechZoid Technologies Private Limited",
    accountNumber: "000000000000",
    ifsc: "SMPL0000001",
    branch: "Pitampura",
  },
  terms: null,
});

writeFileSync(process.argv[2] ?? "/tmp/quotation.pdf", bytes);
console.log(`${bytes.length} bytes`);
